name: calendar
description: Flutter Calendar Component
version: 0.0.2
author: Michael Perrotte
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_flux: '>=4.0.1'
  http: '>=0.11.3+14'


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
